site_name: Domainer.xyz
site_url: https://domainer.xyz
site_description: 域名相关知识
site_author: Matt
repo_url: 
copyright: Copyright &copy; 2019 <a href="https://domainer.xyz">Domainer</a> | Hosted by <a href="http://www.dougalmatthews.com/">Dougal Matthews</a>.
#
nav:
    - Home: index.md
    - About: about.md
theme: windmill #readthedocs

